id: P003268
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:51:30.715534
source_metadata:
  id: bdr:W2PD20566
  title: གསར་བྱུང་མིང་མཛོད་བློ་གསལ་མགྲིན་རྒྱན།
  author: ''
  volumes:
    df84f816c79948a1901f129f3994b836:
      image_group_id: I2PD20745
      title: ''
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
