id: I4D9D00D5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:17:57+00:00'
last_modified: '2022-06-07T18:45:20.082278+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD20566
  title: གསར་བྱུང་མིང་མཛོད་བློ་གསལ་མགྲིན་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    14DE:
      image_group_id: I2PD20745
      title: ''
      total_pages: 226
      order: 1
      base_file: 14DE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
