id: I4D9D00D5
legacy_id: P003268
ocr_import_info:
  bdrc_scan_id: W2PD20566
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T11:16:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:08:18.665677+00:00'
last_modified: 2022-09-03 19:08:26.622266
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD20566
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD20566
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསར་བྱུང་མིང་མཛོད་བློ་གསལ་མགྲིན་རྒྱན།
  author: བསོད་ནམས་དབང་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.7896442115699575
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I2PD20745:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20745
      total_pages: 226
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD20745.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.7896442115699575
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
